/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.transportappgateway.client.transport.api;

import com.illud.transportappgateway.client.transport.model.RiderDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-08-12T12:38:57.877+05:30[Asia/Kolkata]")

@Api(value = "RiderResource", description = "the RiderResource API")
public interface RiderResourceApi {

    @ApiOperation(value = "createRider", nickname = "createRiderUsingPOST", notes = "", response = RiderDTO.class, tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/riders",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<RiderDTO> createRiderUsingPOST(@ApiParam(value = "riderDTO" ,required=true )  @Valid @RequestBody RiderDTO riderDTO);


    @ApiOperation(value = "createriderIfnotExist", nickname = "createriderIfnotExistUsingPOST", notes = "", response = RiderDTO.class, tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/create/riders",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<RiderDTO> createriderIfnotExistUsingPOST(@ApiParam(value = "riderDTO" ,required=true )  @Valid @RequestBody RiderDTO riderDTO);


    @ApiOperation(value = "deleteRider", nickname = "deleteRiderUsingDELETE", notes = "", tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/riders/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteRiderUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllRiders", nickname = "getAllRidersUsingGET", notes = "", response = RiderDTO.class, responseContainer = "List", tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/riders",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RiderDTO>> getAllRidersUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getRider", nickname = "getRiderUsingGET", notes = "", response = RiderDTO.class, tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/riders/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<RiderDTO> getRiderUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchRiders", nickname = "searchRidersUsingGET", notes = "", response = RiderDTO.class, responseContainer = "List", tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/riders",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RiderDTO>> searchRidersUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateRider", nickname = "updateRiderUsingPUT", notes = "", response = RiderDTO.class, tags={ "rider-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RiderDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/riders",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<RiderDTO> updateRiderUsingPUT(@ApiParam(value = "riderDTO" ,required=true )  @Valid @RequestBody RiderDTO riderDTO);

}
